#!/bin/bash -eu

function clone_or_pull() {
  local repo="${1}"
  local location="${2}"
  if [[ -d "${location}" ]]; then
    echo "Pulling ${location}..."
    git -C "${location}" pull
  else
    git clone "${repo}" "${location}"
  fi
}

function install_aur_package() {
  local package="${1}"
  clone_or_pull "https://aur.archlinux.org/${package}.git" "${HOME}/aur/${package}"
  pushd "${HOME}/aur/${package}" > /dev/null
    makepkg -si
  popd > /dev/null
}

function install_aur_packages() {
  for package in $(cat aur-packages);
  do
    install_aur_package ${package}
  done
}

function update_nvim() {
  nvim +PlugInstall +PlugUpdate +PlugUpgrade +qall --headless
}

function main() {

  sudo pacman -Sy --noconfirm $(cat packages)
  install_aur_packages $(cat aur-packages)

  clone_or_pull "https://github.com/chriskempson/base16-shell" "${HOME}/.config/base16-shell"

  update_nvim
}

main
